
services:
  rabbitmq:
    container_name: 'rabbitmq-pdf-generation'
    image: 'rabbitmq:management'
    environment:
      - 'RABBITMQ_DEFAULT_USER=guest'
      - 'RABBITMQ_DEFAULT_PASS=guest'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
